/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.*;

import model.Professor;
import service.ProfessorService;

/**
 * @author julio
 */
public class GUIJFraPrincipal extends javax.swing.JFrame {

    private ProfessorTableModel modelo;
    List<Professor> lista;

    private ProfessorService service;

    /**
     * Creates new form jFraPrincipal
     */
    public GUIJFraPrincipal() {
        initComponents();

        service = new ProfessorService();
        lista = service.findAll();
        modelo = new ProfessorTableModel(lista);
        jTabProfessor.setModel(modelo);
        jTabProfessor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbutAdicionar = new javax.swing.JButton();
        jbutEditar = new javax.swing.JButton();
        jButExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabProfessor = new javax.swing.JTable();
        jTexFieBusca = new javax.swing.JTextField();
        jComBoxParametro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professores Cadastrados");

        jbutAdicionar.setText("Adicionar");
        jbutAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutAdicionarActionPerformed(evt);
            }
        });

        jbutEditar.setText("Editar");
        jbutEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutEditarActionPerformed(evt);
            }
        });

        jButExcluir.setText("Excluir");
        jButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jbutAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbutEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbutAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbutEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());


        jScrollPane1.setViewportView(jTabProfessor);

        jTexFieBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFieBuscaKeyReleased(evt);
            }
        });

        jComBoxParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Nome", "ID"}));

        jLabel1.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComBoxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTexFieBusca))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTexFieBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComBoxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbutAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutAdicionarActionPerformed

        Professor newProfessor = new Professor();
        GUIDadosProfessor entradaDados = new GUIDadosProfessor(this, rootPaneCheckingEnabled, newProfessor);

        entradaDados.setVisible(true);

        modelo.updateTable(service.findAll());
        jTabProfessor.updateUI();
    }//GEN-LAST:event_jbutAdicionarActionPerformed

    private void jbutEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutEditarActionPerformed

        int linha = jTabProfessor.getSelectedRow();

        if (linha != -1) {

            Professor professor = service.findById(modelo.getProfessor(linha).getId());

            GUIDadosProfessor entradaDados = new GUIDadosProfessor(this, rootPaneCheckingEnabled, professor);

            entradaDados.setVisible(true);

            modelo.updateTable(service.findAll());
            jTabProfessor.updateUI();
        }


    }//GEN-LAST:event_jbutEditarActionPerformed

    private void jTexFieBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFieBuscaKeyReleased

        if (jComBoxParametro.getSelectedItem().equals("ID") && !jTexFieBusca.getText().isBlank()) {
            try {

                Professor p = service.findById(Integer.valueOf(jTexFieBusca.getText().trim()));
                if (p != null) {
                    modelo.updateTable(List.of(p));
                }

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "ID invalido!");
                jTexFieBusca.setText("");
            }

        } else {
            modelo.updateTable(service.buscar(jTexFieBusca.getText().trim()));
        }
        jTabProfessor.updateUI();
    }//GEN-LAST:event_jTexFieBuscaKeyReleased

    private void jButExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int linha = jTabProfessor.getSelectedRow();

            if (linha != -1) {

                service.excuir(modelo.getProfessor(linha).getId());
                modelo.updateTable(service.findAll());
                jTabProfessor.updateUI();

            } else {
                JOptionPane.showMessageDialog(this, "Primeiro Selecione a Linha");
            }
        }catch (IndexOutOfBoundsException outOfBoundsException){
            JOptionPane.showMessageDialog(this, "Seleciono uma linha");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButExcluir;
    private javax.swing.JComboBox<String> jComBoxParametro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabProfessor;
    private javax.swing.JTextField jTexFieBusca;
    private javax.swing.JButton jbutAdicionar;
    private javax.swing.JButton jbutEditar;
    // End of variables declaration//GEN-END:variables
}
